pimcore_monitor_system_health_report:
    path: /admin/pimcore-monitor/system-health/report
    defaults: { _controller: Wvision\Bundle\PimcoreMonitorBundle\Controller\Admin\HealthCheckController::health }
    methods:
        - GET

pimcore_monitor_system_health_status:
    path: /admin/pimcore-monitor/system-health/status
    defaults: { _controller: Wvision\Bundle\PimcoreMonitorBundle\Controller\Admin\HealthCheckController::status }
    options:
        expose: true
    methods:
        - GET
